test: add tests summary in ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -17,7 +17,7 @@ jobs:
         mode: [serial, mpi]
 
     steps:
-      # checks out the repository under $GITHUB_WORKSPACE
+      # check out the repository under $GITHUB_WORKSPACE
       # so the job can access it
       - name: checkout
         uses: actions/checkout@v7
@@ -33,7 +33,7 @@ jobs:
         run: sudo apt-get update && sudo apt-get install -y openmpi-bin libopenmpi-dev
 
       - name: cache drunet weights
-        id: weights-cache                  # give this step an id so we can reference it later
+        id: weights-cache                  # give this step an id so it can be referenced later
         uses: actions/cache@v4
         with:
           path: data/weights/drunet/
@@ -54,3 +54,15 @@ jobs:
       - name: run MPI CPU tests
         if: matrix.mode == 'mpi'
         run: pixi run --environment test mpirun -np 2 pytest tests --mode mpi
+
+  # tests summary
+  all-tests-passed:
+    name: all tests passed
+    runs-on: ubuntu-latest
+    needs: cpu-tests
+    if: always() # forced to run even if the matrix above fails
+    steps:
+      - name: Verify matrix success
+        # fail the job if any of the matrix jobs failed
+        if: ${{ needs.cpu-tests.result != 'success' }}
+        run: exit 1
